---
:project: ratio-fix
:suite:
  :name: baseline-POB-course
  :tests:
    :test5:
      :template: basic
      :users: 5
      :name: basic-with-5-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test10:
      :template: basic
      :users: 10
      :name: basic-with-10-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test15:
      :template: basic
      :users: 15
      :name: basic-with-15-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test18:
      :template: basic
      :users: 18
      :name: basic-with-18-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test20:
      :template: basic
      :users: 20
      :name: basic-with-20-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test22:
      :template: basic
      :users: 22
      :name: basic-with-22-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test25:
      :template: basic
      :users: 25
      :name: basic-with-25-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
    :test30:
      :template: basic
      :users: 30
      :name: basic-with-30-users
      :duration: 320
      :postsleep: 300
      :enrollments: "/Users/Gabriel/w/qa-stemeco/stem_eco_api/test/util/rujm/artifacts/SEL-889/0250k/generated_enrollments-first-2000.csv"
      :course_view_count: 3
      :render: graphs1
