INSERT INTO criteria
    (id,
    title,
    description,
    available_to_rubric,
    rubric_level_1,
    rubric_level_2,
    rubric_level_3,
    rubric_level_4,
    draft_goals_1,
    draft_goals_2,
    draft_goals_3,
    draft_goals_4,
    draft_goals_5,
    draft_goals_6,
    created_by_id,
    created_date)
VALUES
    ('4a7e811e-076d-488b-a523-94169c971e6d',
    'Thesis',
    'Lucas ipsum dolor sit amet alderaan obi-wan vader bespin moff palpatine darth anakin skywalker obi-wan.',
    true,
    'Thesis offers a clear and insightful judgment of the text',
    'Thesis offers a judgment of the text',
    'Thesis does not present a critical response to the text',
    'Thesis is buried or unclear',
    'dagobah mace ben calrissian dooku k-3po kamino. Mandalore chewbacca jade jar lando yoda lando.',
    'a han luuke wedge calamari endor thrawn. Hutt moff lobot wedge mon darth',
    'inks. Padmé jabba mon mace jango organa utapau anakin darth',
    'enobi leia skywalker skywalker darth darth solo. Kamino padmé luke grievous jade ben hutt. Windu n',
    's darth binks windu kessel r2-d2 ponda skywalker. Moff organa mustafar aayla ',
    'olo jawa wicket darth ackbar binks jawa ben biggs. Aayla jinn organa qui-gon c',
    gen_random_uuid(),
    NOW());

INSERT INTO criteria
    (id,
    title,
    description,
    available_to_rubric,
    rubric_level_1,
    rubric_level_2,
    rubric_level_3,
    rubric_level_4,
    draft_goals_1,
    draft_goals_2,
    draft_goals_3,
    draft_goals_4,
    draft_goals_5,
    draft_goals_6,
    created_by_id,
    created_date)
VALUES
    ('bd500741-01d1-4ddc-b08b-dea70d55995f',
    'Evidence',
    'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
    true,
    'Well-chosen evidence informs and supports the thesis',
    'Includes relevant evidence, though readers may need more evidence to be convinced',
    'Insufficient evidence',
    'Limited or no evidence',
    'ko mayagil ryn mon wicket maarek fel paploo',
    'ando tono. Xappyh nelvaanian nien piett chadra-fan whitesun. Jerjerrod fode caamasi skywalker. Marek doldur palpatine organa. Illum aleena mantell ahsoka a',
    'moff depa. Ubese jinn dantooine ka beru dug',
    'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whiphid twilek. Ansuroer sly reb',
    'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whi',
    'lig. Vagaari freedon ackbar jax aka. Pol',
    gen_random_uuid(),
    NOW());

INSERT INTO criteria
    (id,
    title,
    description,
    available_to_rubric,
    rubric_level_1,
    rubric_level_2,
    rubric_level_3,
    rubric_level_4,
    draft_goals_1,
    draft_goals_2,
    draft_goals_3,
    draft_goals_4,
    draft_goals_5,
    draft_goals_6,
    created_by_id,
    created_date)
VALUES
    ('3122600f-1c09-4f2d-bf8e-b6e84bfb6b1f',
    'Interpretation/Analysis',
    'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
    true,
    'Clear interpretation and insightful analysis',
    'Interpretation /analysis is accurate and advances the argument',
    'Includes some discussion of how the text makes its point',
    'Limited or no analysis; does not look at how the text makes its point',
    'wicket maarek fel paploo falleen. Moff mustafar garm devaronian mon. Beru zuggs n',
    'ako mayagil ryn mon wicket maarek f',
    'ahsoka antilles yuuzhan quadrinaros r4-p17 mod. Thennqora darpa trio',
    'ese jinn dantooine ka beru dug nelvaanian elomin. Darth calamari elomin derek falleen quadrinar',
    'polis bespin thisspias boz darth talortai. Kiffar hutt x1 jeremoch cody. Darth whill yavin chagrian dantari leia corellia owen elom. Xappyh joruus gotal ahsoka ablajeck troig. Vagaari freedon ackbar jax aka. Polis arkanian chewbacca ruurian m',
    'aleena mantell ahsoka antilles yuuzhan quadrinaros r4-p17 mod. Thennqora darpa trioculus z',
    gen_random_uuid(),
    NOW());

    INSERT INTO criteria
        (id,
        title,
        description,
        available_to_rubric,
        rubric_level_1,
        rubric_level_2,
        rubric_level_3,
        rubric_level_4,
        draft_goals_1,
        draft_goals_2,
        draft_goals_3,
        draft_goals_4,
        draft_goals_5,
        draft_goals_6,
        created_by_id,
        created_date)
    VALUES
        ('6e6743ea-04fc-449e-8af7-8c368bf5c11c',
        'Organization',
        'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
        true,
        'Analysis is well organized, with clear topic sentences and transitions',
        'Well organized on the whole, but occasionally needing work on paragraph coherence or transitions',
        'Connection among ideas is not always clear; there may be more than one point per paragraph',
        'Ideas are difficult to follow',
        'anx ka pellaeon bren subterrel. -1b dor fel carondian ric. Gev mirax jawa darth tapani. Duro quelli luuke togruta shistavanen rune.',
        'rinaros lars epicanthix. Terrik polis bespin thisspias boz dart',
        'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspiasi',
        'issa keshiri owen. Yavin kwa abyssin tython airen trioculus ongree thakwaash gricho. ',
        'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspi',
        'lorine carlist kwa. Wuher shmi nas ubb. Sing logray ryn mustafar valorum lando. ',
        gen_random_uuid(),
        NOW());

    INSERT INTO criteria
        (id,
        title,
        description,
        available_to_rubric,
        rubric_level_1,
        rubric_level_2,
        rubric_level_3,
        rubric_level_4,
        draft_goals_1,
        draft_goals_2,
        draft_goals_3,
        draft_goals_4,
        draft_goals_5,
        draft_goals_6,
        created_by_id,
        created_date)
    VALUES
        ('678ef716-4acf-42d2-bef2-583ceb891bfb',
        'Knowledge of Conventions',
        'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
        true,
        'Fluent, controlled discussion',
        'Sufficient control of grammar, usage, and mechanics',
        'Errors in grammar, usage, or mechanics detract from the writing',
        'Errors in grammar, usage, or mechanics prevent understanding',
        'ino moff. Padmé obi-wan ben boba hutt mandalore wampa yoda. Cade darth bo',
        'walker. Kit r2-d2 solo organa darth skywalker.',
        'go mace qui-gon padmé darth gonk. Hutt moff darth sebulba bothan. Han mustafar calamar',
        'lorians bothan kit. Fett ewok solo kashyyyk darth alderaan fett. Amidala darth tusken raider fett ahsoka. Lobot ',
        'lars yoda coruscant padmé moff kenobi mon vader. Darth windu dantooine wampa antilles g',
        'ker dagobah wedge calamari jinn. Naboo luke dooku mustafar alderaan darth darth orga',
        gen_random_uuid(),
        NOW());

    INSERT INTO criteria
        (id,
        title,
        description,
        available_to_rubric,
        rubric_level_1,
        rubric_level_2,
        rubric_level_3,
        rubric_level_4,
        draft_goals_1,
        draft_goals_2,
        draft_goals_3,
        draft_goals_4,
        draft_goals_5,
        draft_goals_6,
        created_by_id,
        created_date)
    VALUES
        ('f01ed383-78e9-4089-867a-70e8911bbace',
        'Thesis',
        'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
        true,
        'Introduces a focused, arguable thesis',
        'Introduces an arguable thesis that lacks focus',
        'Introduces a vague or broad thesis',
        'Lacks an arguable thesis',
        'ino moff. Padmé obi-wan ben boba hutt mandalore wampa yoda. Cade darth bo',
        'walker. Kit r2-d2 solo organa darth skywalker.',
        'go mace qui-gon padmé darth gonk. Hutt moff darth sebulba bothan. Han mustafar calamar',
        'lorians bothan kit. Fett ewok solo kashyyyk darth alderaan fett. Amidala darth tusken raider fett ahsoka. Lobot ',
        'lars yoda coruscant padmé moff kenobi mon vader. Darth windu dantooine wampa antilles g',
        'ker dagobah wedge calamari jinn. Naboo luke dooku mustafar alderaan darth darth orga',
        gen_random_uuid(),
        NOW());


        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('91db94ee-a6f1-4be5-911c-9e7b8b992531',
            'Claims',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Claims clearly relate to thesis',
            'Introduces relevant claims that need further development',
            'Introduces claims that do not all support the thesis',
            'Lacks sufficient claims to support thesis',
            'anx ka pellaeon bren subterrel. -1b dor fel carondian ric. Gev mirax jawa darth tapani. Duro quelli luuke togruta shistavanen rune.',
            'rinaros lars epicanthix. Terrik polis bespin thisspias boz dart',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspiasi',
            'issa keshiri owen. Yavin kwa abyssin tython airen trioculus ongree thakwaash gricho. ',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspi',
            'lorine carlist kwa. Wuher shmi nas ubb. Sing logray ryn mustafar valorum lando. ',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('1740b6d4-e13d-4ea0-ad17-545bb4bb9546',
            'Evidence',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Evidence supports claims and is well-chosen',
            'Evidence supports claim',
            'Evidence does not support claim',
            'Limited or no evidence',
            'ko mayagil ryn mon wicket maarek fel paploo',
            'ando tono. Xappyh nelvaanian nien piett chadra-fan whitesun. Jerjerrod fode caamasi skywalker. Marek doldur palpatine organa. Illum aleena mantell ahsoka a',
            'moff depa. Ubese jinn dantooine ka beru dug',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whiphid twilek. Ansuroer sly reb',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whi',
            'lig. Vagaari freedon ackbar jax aka. Pol',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('dd6f10e6-f07d-4c70-b5c6-2a3c5e3d35e9',
            'Logical appeals',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Develops multiple effective appeals',
            'Develops an effective appeal',
            'Introduces an effective appeal that needs further development',
            'Uses weak or no appeals',
            'dagobah mace ben calrissian dooku k-3po kamino. Mandalore chewbacca jade jar lando yoda lando.',
            'a han luuke wedge calamari endor thrawn. Hutt moff lobot wedge mon darth',
            'inks. Padmé jabba mon mace jango organa utapau anakin darth',
            'enobi leia skywalker skywalker darth darth solo. Kamino padmé luke grievous jade ben hutt. Windu n',
            's darth binks windu kessel r2-d2 ponda skywalker. Moff organa mustafar aayla ',
            'olo jawa wicket darth ackbar binks jawa ben biggs. Aayla jinn organa qui-gon c',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('02a8ae4e-2ae3-4390-bcb5-cadb6324567a',
            'Counterargument',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Develops a credible counterargument and addresses it adequately',
            'Introduces a credible counterargument',
            'Introduces a weak counterargument',
            'Does not address counterarguments',
            'ko mayagil ryn mon wicket maarek fel paploo',
            'ando tono. Xappyh nelvaanian nien piett chadra-fan whitesun. Jerjerrod fode caamasi skywalker. Marek doldur palpatine organa. Illum aleena mantell ahsoka a',
            'moff depa. Ubese jinn dantooine ka beru dug',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whiphid twilek. Ansuroer sly reb',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whi',
            'lig. Vagaari freedon ackbar jax aka. Pol',
            gen_random_uuid(),
            NOW());

           INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('c54305f8-6605-4021-92e5-0a03b4ef22fe',
            'Ideas/Content',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Tells a compelling story with a clear sense of purpose',
            'Tells a clear story that lacks focus on purpose',
            'Ideas are present but largely disconnected from a central narrative',
            'Lacks coherent ideas and sense of purpose',
            'wicket maarek fel paploo falleen. Moff mustafar garm devaronian mon. Beru zuggs n',
            'ako mayagil ryn mon wicket maarek f',
            'ahsoka antilles yuuzhan quadrinaros r4-p17 mod. Thennqora darpa trio',
            'ese jinn dantooine ka beru dug nelvaanian elomin. Darth calamari elomin derek falleen quadrinar',
            'polis bespin thisspias boz darth talortai. Kiffar hutt x1 jeremoch cody. Darth whill yavin chagrian dantari leia corellia owen elom. Xappyh joruus gotal ahsoka ablajeck troig. Vagaari freedon ackbar jax aka. Polis arkanian chewbacca ruurian m',
            'aleena mantell ahsoka antilles yuuzhan quadrinaros r4-p17 mod. Thennqora darpa trioculus z',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('4659528b-487d-46b5-b4d6-bbc4fcd57c7f',
            'Genre',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Chooses a relevant sequence, structure, and designn',
            'Shows a more basic understanding of narrative conventions',
            'Suitable understanding of some conventions mixed with misunderstanding of others',
            'Lacks understanding of narrative conventions',
            'anx ka pellaeon bren subterrel. -1b dor fel carondian ric. Gev mirax jawa darth tapani. Duro quelli luuke togruta shistavanen rune.',
            'rinaros lars epicanthix. Terrik polis bespin thisspias boz dart',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspiasi',
            'issa keshiri owen. Yavin kwa abyssin tython airen trioculus ongree thakwaash gricho. ',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspi',
            'lorine carlist kwa. Wuher shmi nas ubb. Sing logray ryn mustafar valorum lando. ',
            gen_random_uuid(),
            NOW());

           INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('98f8e2b6-0252-4d33-b9e3-d11ee333250a',
            'Style/Voice',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Well-developed sense pacing, style, and voice',
            'Elements of style and voice are present but inconsistent',
            'Elements of style or voice are present but don’t support the narrative',
            'No clear sense of pacing, style, or voice present',
            'dagobah mace ben calrissian dooku k-3po kamino. Mandalore chewbacca jade jar lando yoda lando.',
            'a han luuke wedge calamari endor thrawn. Hutt moff lobot wedge mon darth',
            'inks. Padmé jabba mon mace jango organa utapau anakin darth',
            'enobi leia skywalker skywalker darth darth solo. Kamino padmé luke grievous jade ben hutt. Windu n',
            's darth binks windu kessel r2-d2 ponda skywalker. Moff organa mustafar aayla ',
            'olo jawa wicket darth ackbar binks jawa ben biggs. Aayla jinn organa qui-gon c',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('0d674a3e-e61c-41d9-99fb-738882f58f13',
            'Word choice',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Keen observation and description of details and setting',
            'Adequate attention to details and setting',
            'Limited attention to details and setting',
            'Little to no attention to details and setting',
            'ko mayagil ryn mon wicket maarek fel paploo',
            'ando tono. Xappyh nelvaanian nien piett chadra-fan whitesun. Jerjerrod fode caamasi skywalker. Marek doldur palpatine organa. Illum aleena mantell ahsoka a',
            'moff depa. Ubese jinn dantooine ka beru dug',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whiphid twilek. Ansuroer sly reb',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whi',
            'lig. Vagaari freedon ackbar jax aka. Pol',
            gen_random_uuid(),
            NOW());

         INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('30a2b72b-153b-449e-ae75-6d52417d5fd8',
            'Conclusion',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Clearly evokes the importance of the writers experiences',
            'Attempts to convey the importance of  the writers experiences',
            'Importance of experiences conveyed does not support the rest of the narrative',
            'No clear sense of importance of what has been narrated',
            'anx ka pellaeon bren subterrel. -1b dor fel carondian ric. Gev mirax jawa darth tapani. Duro quelli luuke togruta shistavanen rune.',
            'rinaros lars epicanthix. Terrik polis bespin thisspias boz dart',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspiasi',
            'issa keshiri owen. Yavin kwa abyssin tython airen trioculus ongree thakwaash gricho. ',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspi',
            'lorine carlist kwa. Wuher shmi nas ubb. Sing logray ryn mustafar valorum lando. ',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('cff30bcb-0425-4d06-98d3-c22f2bd10a79',
            'Issue',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Clearly describes a problem and communicates the nature, scope, and urgency of the problem',
            'Describes a specific problem and need for action',
            'Does not describe the problem in enough detail: readers do not see a compelling need for action',
            'Does not identify or describe a specific problem',
             'ino moff. Padmé obi-wan ben boba hutt mandalore wampa yoda. Cade darth bo',
             'walker. Kit r2-d2 solo organa darth skywalker.',
             'go mace qui-gon padmé darth gonk. Hutt moff darth sebulba bothan. Han mustafar calamar',
             'lorians bothan kit. Fett ewok solo kashyyyk darth alderaan fett. Amidala darth tusken raider fett ahsoka. Lobot ',
             'lars yoda coruscant padmé moff kenobi mon vader. Darth windu dantooine wampa antilles g',
             'ker dagobah wedge calamari jinn. Naboo luke dooku mustafar alderaan darth darth orga',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('37f0de46-357a-442b-9859-fa07fc9e47a9',
            'Genre',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Form and language meet the needs of the intended audience',
            'Shows a basic understanding of the genres conventions',
            'Suitable understanding of some conventions mixed with misundestanding of others',
            'Lacks understanding of the genres conventions',
            'anx ka pellaeon bren subterrel. -1b dor fel carondian ric. Gev mirax jawa darth tapani. Duro quelli luuke togruta shistavanen rune.',
            'rinaros lars epicanthix. Terrik polis bespin thisspias boz dart',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspiasi',
            'issa keshiri owen. Yavin kwa abyssin tython airen trioculus ongree thakwaash gricho. ',
            'Bibble ansion nunb keshiri jango. Charal drovian kyp ozzel freedon thisspi',
            'lorine carlist kwa. Wuher shmi nas ubb. Sing logray ryn mustafar valorum lando. ',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('dd5ee9ca-8c2c-4a81-941a-a3a0d8bb3be2',
            'Support',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Incorporate appropriate evidence to convince the audience that the solution is feasible',
            'Provides adequate support for recommendations',
            'Lacking sufficient support for recommendations',
            'Limited or no support for recommendations',
            'wicket maarek fel paploo falleen. Moff mustafar garm devaronian mon. Beru zuggs n',
            'ako mayagil ryn mon wicket maarek f',
            'ahsoka antilles yuuzhan quadrinaros r4-p17 mod. Thennqora darpa trio',
            'ese jinn dantooine ka beru dug nelvaanian elomin. Darth calamari elomin derek falleen quadrinar',
            'polis bespin thisspias boz darth talortai. Kiffar hutt x1 jeremoch cody. Darth whill yavin chagrian dantari leia corellia owen elom. Xappyh joruus gotal ahsoka ablajeck troig. Vagaari freedon ackbar jax aka. Polis arkanian chewbacca ruurian m',
            'aleena mantell ahsoka antilles yuuzhan quadrinaros r4-p17 mod. Thennqora darpa trioculus z',
            gen_random_uuid(),
            NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('116e3415-4550-41ba-b976-883d34b844d7',
            'Comparisons/Counterarguments',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Examines prior solutions and weighs all reasonable alternatives',
            'Adequately describes the history of the issue and mentions alternative solutions',
            'Limited attention paid to the issues history or to alternative solutions',
            'Little to no attention paid to the issues context or to alternative solutions',
            'ko mayagil ryn mon wicket maarek fel paploo',
            'ando tono. Xappyh nelvaanian nien piett chadra-fan whitesun. Jerjerrod fode caamasi skywalker. Marek doldur palpatine organa. Illum aleena mantell ahsoka a',
            'moff depa. Ubese jinn dantooine ka beru dug',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whiphid twilek. Ansuroer sly reb',
            'needa frozian rom jerec porkins. Terentatek mothma drachnam asajj kal. Skywalker omwati whi',
            'lig. Vagaari freedon ackbar jax aka. Pol',
             gen_random_uuid(),
             NOW());

        INSERT INTO criteria
            (id,
            title,
            description,
            available_to_rubric,
            rubric_level_1,
            rubric_level_2,
            rubric_level_3,
            rubric_level_4,
            draft_goals_1,
            draft_goals_2,
            draft_goals_3,
            draft_goals_4,
            draft_goals_5,
            draft_goals_6,
            created_by_id,
            created_date)
        VALUES
            ('fb620970-3a37-4a2b-ab58-d328d8862117',
            'Recommendations',
            'a watto. C-3po ahsoka jango ben darth solo skywalker skywalker jade. Dantooine fisto fett dantooine palpatine gonk. Antill',
            true,
            'Makes realistic recommendations and provides a plausible pathway to completion',
            'Makes recommendations that need further development',
            'Recommendations or approach is somewhat flawed',
            'Does not make specific recommendations',
            'dagobah mace ben calrissian dooku k-3po kamino. Mandalore chewbacca jade jar lando yoda lando.',
            'a han luuke wedge calamari endor thrawn. Hutt moff lobot wedge mon darth',
            'inks. Padmé jabba mon mace jango organa utapau anakin darth',
            'enobi leia skywalker skywalker darth darth solo. Kamino padmé luke grievous jade ben hutt. Windu n',
            's darth binks windu kessel r2-d2 ponda skywalker. Moff organa mustafar aayla ',
            'olo jawa wicket darth ackbar binks jawa ben biggs. Aayla jinn organa qui-gon c',
            gen_random_uuid(),
            NOW());
