version: "2"
services:
  wk_frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run start
    env_file:
      - ./.env
    environment:
      APPLICATION_NAME: wk_frontend
    ports:
      - "8080:8080"

  frontend_test:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run test
    environment:
      DEBUG: 'true'
      NODE_ENV: development
      APPLICATION_NAME: wk_frontend
    ports:
      - "8080:8080"
