sls_course_builder_api:
  image: sls_course_builder_api
  volumes:
    - ./../app:/home/current/app
  command: npm start #top -b #
 # external_links:
  #  - cdn:frontend
  environment:
    DEBUG: 'true'
    NODE_ENV: development
    APPLICATION_NAME: sls_course_builder_api
  ports:
    - "3000:3000"