version: "2"
services:
  wk_serve:
    image: ${wk_serve_image}
    command: npm run start_dev
    env_file:
      - ./.env
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: wk_serve
    ports:
      - "4777:4777"
    container_name: wk_serve
