version: "2"
services:
  data:
    extends:
      file: ../../wk_data/docker/docker-compose.yml
      service: wk_data
    container_name: wk_data
  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    container_name: postgres
