sls_course_builder_api_test:
  image: sls_course_builder_api
  volumes:
    - ./../app:/home/current/app
  command: npm test #top -b #
 # external_links:
  #  - cdn:frontend
  environment:
    DEBUG: 'true'
    NODE_ENV: test
    APPLICATION_NAME: sls_course_builder_api
  ports:
    - "3000:3000"
