version: "2"
services:
  frontend:
    image: ${wk_frontend_image}
    extends:
      file: ./docker-compose.yml
      service: frontend

  api:
    image: ${wk_api_image}
    extends:
      file: ./docker-compose.yml
      service: api

  data:
    image: ${wk_data_image}
    extends:
      file: ./docker-compose.yml
      service: data

  serve:
    image: ${wk_serve_image}
    extends:
      file: ./docker-compose.yml
      service: serve

  swaggerUi:
    extends:
      file: ./docker-compose.yml
      service: swaggerUi
