version: "2"
services:
  frontend:
    extends:
      file: ./docker-compose.yml
      service: frontend
    image: ${wk_frontend_image}

  api:
    extends:
      file: ./docker-compose.yml
      service: api
    image: ${wk_api_image}

  data:
    extends:
      file: ./docker-compose.yml
      service: data
    image: ${wk_data_image}

  serve:
    extends:
      file: ./docker-compose.yml
      service: serve
    image: ${wk_serve_image}

  swaggerUi:
    extends:
      file: ./docker-compose.yml
      service: swaggerUi
