version: "2"
services:
  wk_api:
    image: wk_api
    volumes:
      - ./../app:/home/current/app
    command: npm run start_dev #top -b #top -b #
   # external_links:
    #  - cdn:frontend
    env_file:
      - ../.env
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: wk_api
    ports:
      - "3000:3000"
  postgres:
      image: postgres
      environment:
        - LANG=en_US.UTF-8
        - POSTGRES_PASSWORD=writer_key
        - POSTGRES_USER=writer_key
      ports:
        - 5432:5432
