version: "2"
services:
  front_end:
    extends:
      file: ../../wk_frontend/docker/docker-compose.yml
      service: wk_frontend
    container_name: wk_frontend

  api:
    extends:
      file: ../../wk_api/docker/docker-compose.yml
      service: wk_api
    container_name: wk_api

  data:
    extends:
      file: ../../wk_data/docker/docker-compose.yml
      service: wk_data
    container_name: wk_data

  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432

  nginx:
    image: nginx_container
    ports:
      - "10080:80"
    container_name: nginx_container
