version: "2"
services:
  data:
    depends_on:
      - postgres
      - front_end
      - api
    extends:
      file: ../../wk_data/docker/docker-compose.yml
      service: wk_data
    container_name: wk_data

  front_end:
    extends:
      file: ../../wk_frontend/docker/docker-compose.yml
      service: wk_frontend
    container_name: wk_frontend

  api:
    extends:
      file: ../../wk_api/docker/docker-compose-dev.yml
      service: wk_api
    container_name: wk_api

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./../.env
    container_name: postgres

  nginx:
    image: nginx_container
    ports:
      - "10080:80"
    container_name: nginx_container
