version: "2"
services:
  frontend:
    environment:
      APPLICATION_NAME: wk_frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    image: ${wk_frontend_image}
    env_file:
      - ./.env

  api:
    environment:
      APPLICATION_NAME: wk_api
      POSTGRES_HOST: postgres
    ports:
      - "${API_PORT}:${API_PORT}"
    image: ${wk_api_image}
    env_file:
      - ./.env

  data:
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "${TESTING_API_PORT}:${TESTING_API_PORT}"
    image: ${wk_data_image}
    env_file:
      - ./.env

  serve:
    environment:
      APPLICATION_NAME: wk_serve
      WK_API_URL: http://api:3000
    ports:
      - "${SERVE_PORT}:${SERVE_PORT}"
    image: ${wk_serve_image}
    env_file:
      - ./.env

  swaggerUi:
    image: schickling/swagger-ui
    environment:
      API_URL: "http://localhost:3000/swagger"
      PORT: 4666
    ports:
      - "${SWAGGER_PORT}:${SWAGGER_PORT}"
