version: "2"
services:
  wk_data:
    image: wk_data
    volumes:
      - ./../app:/home/current/app
    #command: "bash && yarn run start"
    entrypoint: bash
    env_file:
      - ./.env
    container_name: wk_data
    tty: true
    stdin_open: true
