version: "2"
services:
  wk_prodtools:
    image: wk_prodtools
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run start
    env_file:
      - ./.env
    environment:
      APPLICATION_NAME: wk_prodtools
    ports:
      - "8081:8081"
    container_name: wk_prodtools

  prodtools_test:
    image: wk_prodtools
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run test
    environment:
      DEBUG: 'true'
      NODE_ENV: development
      APPLICATION_NAME: wk_prodtools
    ports:
      - "8081:8081"
    container_name: wk_prodtools_test
