version: "2"
services:
  selenium-grid:
    image: elgalu/selenium
    env_file:
      - ./.env
    ports:
      - 4444:24444
      - 5900:25900
    volumes:
      - /dev/shm:/dev/shm
    container_name: selenium-grid
  wk_test:
    image: 999447569257.dkr.ecr.us-east-1.amazonaws.com/wk/test:latest
    env_file:
      - ./.env
    command: /bin/sh -c "sleep 5; cat bambooqa.config.json; export TEST_ENV=bambooqa; npm test"
    volumes_from:
      - selenium-grid
    links:
      - selenium-grid
