version: "2"
services:
  frontend:
    environment:
      APPLICATION_NAME: wk_frontend
    ports:
      - "8080:8080"
    image: ${wk_frontend_image}
    networks:
      - writing_network
    env_file:
      - ./.env

  api:
    environment:
      APPLICATION_NAME: wk_api
      POSTGRES_HOST: postgres
    ports:
      - "3000:3000"
    image: ${wk_api_image}
    networks:
      - writing_network
    env_file:
      - ./.env

  data:
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "4667:4667"
    image: ${wk_data_image}
    networks:
      - writing_network
    env_file:
      - ./.env

  serve:
    environment:
      APPLICATION_NAME: wk_serve
      WK_API_URL: http://api:3000
    ports:
      - "10080:10080"
    image: ${wk_serve_image}
    networks:
      - writing_network
    env_file:
      - ./.env

  swaggerUi:
    image: schickling/swagger-ui
    environment:
      API_URL: "http://localhost:3000/swagger"
      PORT: 4666
    ports:
      - "4666:4666"
    networks:
      - writing_network

# Force docker to use 172.20 reserved IPs to not conflict with our VPCs
networks:
  writing_network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.101.0/24
          ip_range: 172.20.101.0/24
          gateway: 172.20.101.1
