version: "2"
services:
  wk_frontend:
    image: wk_frontend
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run start
    env_file:
      - ./.env
    environment:
      APPLICATION_NAME: wk_frontend
    ports:
      - "8080:8080"
    container_name: wk_frontend

  frontend_test:
    image: wk_frontend
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run test
    environment:
      DEBUG: 'true'
      NODE_ENV: development
      APPLICATION_NAME: wk_frontend
    ports:
      - "8080:8080"
    container_name: wk_frontend_test
