version: "2"
services:
  frontend:
      build:
        context: ./../frontend/
        dockerfile: docker/Dockerfile
      image: ${wk_frontend_image}
      command: yarn run start
      env_file:
        - ./.envrc.example
      environment:
        APPLICATION_NAME: wk_frontend
      ports:
        - "8080:8080"
  api:
      build:
        context: ./../api/
        dockerfile: docker/Dockerfile
      image: ${wk_api_image}
      command: yarn run start
      env_file:
        - ./.envrc.example
      environment:
        DEBUG: "true"
        NODE_ENV: development
        APPLICATION_NAME: wk_api
        POSTGRES_HOST: postgres
      ports:
        - "3000:3000"

  data:
      build:
        context: ./../data/
        dockerfile: docker/Dockerfile
      image: ${wk_data_image}
      command: yarn run start
      env_file:
        - ./.envrc.example
      ports:
        - "4667:4667"

  serve:
      build:
        context: ./../serve/
        dockerfile: docker/Dockerfile
      image: ${wk_serve_image}
      command: yarn run start
      env_file:
        - ./.envrc.example
      environment:
        DEBUG: "true"
        NODE_ENV: development
        APPLICATION_NAME: wk_serve
        WK_API_URL: http://api:3000
      ports:
        - "10080:10080"

  swaggerUi:
    image: schickling/swagger-ui
    environment:
      API_URL: "http://localhost:3000/swagger"
      PORT: 4666
    ports:
      - "4666:4666"
