version: "2"
services:
  wk_data:
    image: wk_data
    volumes:
      - ./../app:/home/current/app
    command: "yarn run start"
#    entrypoint: bash
    env_file:
      - ./.env
    container_name: wk_data
