version: "2"
services:
  front_end:
    extends:
      file: ../../wk_frontend/docker/docker-compose.yml
      service: wk_frontend
    container_name: wk_frontend

  api:
    extends:
      file: ../../wk_api/docker/docker-compose.yml
      service: wk_api
    container_name: wk_api

  launch:
    extends:
      file: ../../wk_launch/docker/docker-compose.yml
      service: wk_launch
    container_name: wk_launch

  data:
    extends:
      file: ../../wk_data/docker/docker-compose.yml
      service: wk_data
    container_name: wk_data

  launch:
    extends:
      file: ../../wk_launch/docker/docker-compose.yml
      service: wk_launch
    container_name: wk_launch

  swagger_ui:
    image: schickling/swagger-ui
    environment:
      API_URL: "http://localhost:3000/swagger"
      PORT: 80
    container_name: swagger_ui
    ports:
      - "4666:80"
  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    container_name: postgres

  nginx:
    image: nginx_container
    ports:
      - "10080:80"
    container_name: nginx_container
