version: "2"
services:
  frontend:
      build:
        context: ./../frontend/
        dockerfile: docker/Dockerfile
      volumes:
        - ./../frontend/app:/home/current/app:rw
      env_file:
        - ./../.envrc.example
      environment:
        APPLICATION_NAME: wk_frontend
      ports:
        - "8080:8080"
  api:
      build:
        context: ./../api/
        dockerfile: docker/Dockerfile
      volumes:
        - ./../api/app:/home/current/app:rw
      env_file:
        - ./../.envrc.example
      environment:
        APPLICATION_NAME: wk_api
        POSTGRES_HOST: postgres
      ports:
        - "80:80"

  data:
      build:
        context: ./../data/
        dockerfile: docker/Dockerfile
      volumes:
        - ./../data/app:/home/current/app
        - ./../data/migrations:/home/current/migrations
      env_file:
        - ./../.envrc.example
      environment:
        POSTGRES_HOST: postgres
      ports:
        - "4667:4667"

  serve:
      build:
        context: ./../serve/
        dockerfile: docker/Dockerfile
      volumes:
        - ./../serve/app:/home/current/app:rw
      env_file:
        - ./../.envrc.example
      environment:
        APPLICATION_NAME: wk_serve
        WK_API_URL: http://api/api
      ports:
        - "10080:10080"

  swaggerUi:
    image: schickling/swagger-ui
    environment:
      API_URL: "http://api/swagger"
      PORT: 4666
    ports:
      - "4666:4666"

  postgres:
    image: postgres
    env_file:
      - ./../.envrc.example
    ports:
      - 5433:5432
