version: "2"
services:
  wk_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run start
    env_file:
      - ./.env
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: wk_api
    ports:
      - "3000:3000"
