version: "2"
services:
  wk_serve:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - ./../app:/home/current/app:rw
    command: yarn run start_dev
    env_file:
      - ./.env
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: wk_serve
    ports:
      - "10080:80"
