# probably only necessary for a brief period of time
# where we set up the 'HA' environment to test moving the prod
# filesystem to gluster.
---
  business_units:
    haydenMcNeil:
      lms:
        baseurl: 'https://courses.hayden-mcneil.macmillantech.com'
        realpassword: 'Password123!'
      lmsdb:
        type: 'mysql'
        host: 'stem-hm-rds-prod.internal.macmillantech.com'
        database: 'moodle'
        user: 'admin'
        password: 'bo7A7G7NpAJGtE'
    #   tpapi:
    #     blank: 45
  ecoapi:
    baseurl: 'http://stem-eco-api-test.macmillantech.com'
    # users:
    #   dynamicBooks: 'password'
    #   haydenMcNeil: 'test123'
    db:
      type: 'mysql'
      host: 'stem-eco-api-rds-test.internal.macmillantech.com'
      database: 'eco'
      user: 'root'
      password: 'iZBeptyeZiAjp7wsDGY2'
  # gateway:
  #   ltiprefix: ''
  #   db:
  #     type: 'mysql'
  #     host: '172.20.0.20'
  #     database: 'mnv_gateway'
  #     user: 'root'
  #     password: 'ravenapplestrongpig'
