export const EXPAND_SECTION = 'EXPAND_SECTION';

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_FAILURE = 'COURSE_FAILURE';

export const SWAGGER_REQUEST = 'SWAGGER_REQUEST';
export const SWAGGER_SUCCESS = 'SWAGGER_SUCCESS';
export const SWAGGER_FAILURE = 'SWAGGER_FAILURE';

export const LAST_FETCHED = 'LAST_FETCHED';

// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
