export const EXPAND_CHAPTER = 'EXPAND_CHAPTER';

export const COURSE_REQUEST = 'COURSE_REQUEST';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_FAILURE = 'COURSE_FAILURE';


export const SELECT_COURSE_FROM_MENU = 'SELECT_COURSE_FROM_MENU';

// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
// export const COURSE_MENU_HOVER = 'COURSE_MENU_HOVER'
