version: "2"
services:
  front_end:
    image: ${wk_frontend_image}
    command: npm start
    env_file:
      - .env
    environment:
      APPLICATION_NAME: wk_frontend
    ports:
      - "8080:8080"
    service: wk_frontend
    container_name: wk_frontend
  prodtools:
    image: ${wk_prodtools_image}
    command: npm start
    env_file:
      - .env
    environment:
      APPLICATION_NAME: wk_prodtools
    ports:
      - "8081:8081"
    service: wk_prodtools
    container_name: wk_prodtools
api:
  image: ${wk_api}
    command: npm run start
    env_file:
      - .env
    environment:
      DEBUG: "true"
      NODE_ENV: development
      APPLICATION_NAME: wk_api
    ports:
      - "3000:3000"
    service: wk_api
    container_name: wk_api
	logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
  data:
    image: ${wk_data_image}
    command: npm start
    env_file:
      - .env
    service: wk_data
    container_name: wk_data
  serve:
    image: ${wk_serve_image}
    ports:
      - "80:80"
	service: wk_serve
    container_name: wk_serve
